name: Build EXE with PyInstaller

on:  [push]

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller -F -i "exeicon.ico" --add-data "templates=templates" --add-data "static=static" --add-data "generator.db=generator.db" main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project_EXE
          path: dist/main.exe
